name: build

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - run: ./gradlew build
      - uses: codecov/codecov-action@v4
        with:
          directory: build/reports/jacoco/
          token: ${{ secrets.CODECOV_TOKEN }}
